import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const html = read('index.html');

test('the social preview image is a raster PNG, not an SVG', () => {
  // Facebook, LinkedIn, WhatsApp and X render NO preview at all for an SVG
  // og:image — which for a social-media product is the worst possible bug.
  assert.match(html, /property="og:image" content="[^"]+\.png"/);
  assert.match(html, /name="twitter:image" content="[^"]+\.png"/);
  assert.doesNotMatch(html, /og:image" content="[^"]+\.svg"/);
  assert.doesNotMatch(html, /twitter:image" content="[^"]+\.svg"/);
});

test('the og-image PNG exists and is the expected 1200x630', () => {
  const png = readFileSync(new URL('../public/og-image.png', import.meta.url));
  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a', 'must be a real PNG');
  // IHDR width/height live at bytes 16..24.
  assert.equal(png.readUInt32BE(16), 1200);
  assert.equal(png.readUInt32BE(20), 630);
  // Facebook rejects images over 8MB.
  assert.ok(statSync(new URL('../public/og-image.png', import.meta.url)).size < 8 * 1024 * 1024);
});

test('og:image dimensions are declared so crawlers render the card on first fetch', () => {
  assert.match(html, /property="og:image:width" content="1200"/);
  assert.match(html, /property="og:image:height" content="630"/);
  assert.match(html, /property="og:url"/);
  assert.match(html, /property="og:site_name"/);
});

test('the preview art does not advertise the wrong image engine', () => {
  // Posters are generated by Graphiste GPT; the card used to claim
  // "Images GPT Image 2", which is only a fallback model in _shared/ai.ts.
  const svg = read('public/og-image.svg');
  assert.doesNotMatch(svg, /GPT Image 2/);
  assert.match(svg, /Graphiste GPT/);
  // An SVG without width/height rasterises letterboxed.
  assert.match(svg, /<svg[^>]*width="1200"[^>]*height="630"/);
});

test('crawlers are kept out of the authenticated app', () => {
  const robots = read('public/robots.txt');
  for (const route of ['/dashboard', '/profile', '/admin', '/auth', '/onboarding']) {
    assert.ok(robots.includes(`Disallow: ${route}`), `${route} must not be indexable`);
  }
  assert.match(robots, /Sitemap: https:\/\/\S+\/sitemap\.xml/);
});

test('the sitemap lists only public routes', () => {
  const sitemap = read('public/sitemap.xml');
  for (const route of ['/dashboard', '/profile', '/admin', '/onboarding']) {
    assert.ok(!sitemap.includes(`${route}<`), `${route} must not be in the sitemap`);
  }
  assert.match(sitemap, /<loc>[^<]+\/faq<\/loc>/);
});

test('a JS-disabled visitor sees an explanation rather than a blank page', () => {
  assert.match(html, /<noscript>/);
  assert.match(html, /JavaScript/);
});
