-- =====================================================================
-- Make the validation-link expiry actually work.
--
-- posts.validation_token has had a DEFAULT gen_random_uuid() since
-- 20251203, but validation_token_created_at was only ever BACKFILLED once
-- (20260520) and given no default. Every post created since then carries a
-- token with a NULL creation date, and validate-post skips the TTL check
-- when that column is null — so the documented 24h expiry has never
-- applied to a single real post. Those links are permanent: anyone who
-- gets hold of the URL (forwarded mail, shared inbox, mail scanner logs)
-- can validate the post at any point in the future.
-- =====================================================================

-- 1. Stamp the token's age at insert time, for every future post.
ALTER TABLE public.posts
  ALTER COLUMN validation_token_created_at SET DEFAULT now();

-- 2. Give existing tokens a creation date so the TTL starts applying to
--    them too. created_at is the honest value: the token was generated by
--    the column default at insert.
UPDATE public.posts
SET validation_token_created_at = created_at
WHERE validation_token IS NOT NULL
  AND validation_token_created_at IS NULL;

-- 3. Index the lookup validate-post does on every email click. Without it
--    each validation is a sequential scan over the whole posts table.
--    (An index on validation_token already exists from 20251203; this one
--    covers the send-validation-email batch query instead.)
CREATE INDEX IF NOT EXISTS idx_posts_pending_validation
  ON public.posts (status, validation_email_sent_at)
  WHERE validation_token IS NOT NULL;
